export const mockMovieResponse = [
  {
    adult: false,
    backdrop_path: "/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
    genre_ids: [28, 12, 14],
    id: 566525,
    original_language: "en",
    original_title: "Shang-Chi and the Legend of the Ten Rings",
    overview:
      "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
    popularity: 7750.478,
    poster_path: "/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
    release_date: "2021-09-01",
    title: "Shang-Chi and the Legend of the Ten Rings",
    video: false,
    vote_average: 7.9,
    vote_count: 3181,
  },
  {
    adult: false,
    backdrop_path: "/7WJjFviFBffEJvkAms4uWwbcVUk.jpg",
    genre_ids: [12, 14, 35, 28],
    id: 451048,
    original_language: "en",
    original_title: "Jungle Cruise",
    overview:
      "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.",
    popularity: 715.808,
    poster_path: "/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg",
    release_date: "2021-07-28",
    title: "Jungle Cruise",
    video: false,
    vote_average: 7.7,
    vote_count: 3319,
  },
];

export const mockTVResponse = [
  {
    backdrop_path: "/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
    first_air_date: "2021-11-06",
    genre_ids: [16, 10765, 10759],
    id: 94605,
    name: "Arcane",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Arcane",
    overview:
      "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    popularity: 2432.614,
    poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    vote_average: 9.2,
    vote_count: 654,
  },
  {
    backdrop_path: "/qw3J9cNeLioOLoR68WX7z79aCdK.jpg",
    first_air_date: "2021-09-17",
    genre_ids: [10759, 9648, 18],
    id: 93405,
    name: "Squid Game",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "오징어 게임",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games—with high stakes. But, a tempting prize awaits the victor.",
    popularity: 1665.614,
    poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    vote_average: 7.8,
    vote_count: 9011,
  },
];
